"""Initial Ava schema. Frozen: future changes need a new migration."""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admins_business_id'), 'admins', ['business_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('caller_phone', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('transport', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_status', sa.String(length=30), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'external_id')
    )
    op.create_index(op.f('ix_calls_business_id'), 'calls', ['business_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'key')
    )
    op.create_index(op.f('ix_operations_business_id'), 'operations', ['business_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('call_id', sa.String(length=32), nullable=True),
    sa.Column('caller_name', sa.String(length=120), nullable=False),
    sa.Column('caller_phone', sa.String(length=50), nullable=False),
    sa.Column('caller_email', sa.String(length=254), nullable=False),
    sa.Column('service_id', sa.String(length=40), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id')
    )
    op.create_index(op.f('ix_appointments_business_id'), 'appointments', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_at'), 'appointments', ['start_at'], unique=False)
    op.create_table('login_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('admin_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('call_id', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('caller_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('escalated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'key')
    )
    op.create_index(op.f('ix_messages_business_id'), 'messages', ['business_id'], unique=False)
    op.create_table('transcript_turns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('call_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('delivery', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_turns_business_id'), 'transcript_turns', ['business_id'], unique=False)
    op.create_index(op.f('ix_transcript_turns_call_id'), 'transcript_turns', ['call_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_turns_call_id'), table_name='transcript_turns')
    op.drop_index(op.f('ix_transcript_turns_business_id'), table_name='transcript_turns')
    op.drop_table('transcript_turns')
    op.drop_index(op.f('ix_messages_business_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('login_sessions')
    op.drop_index(op.f('ix_appointments_start_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_business_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_operations_business_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_calls_business_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_admins_business_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('businesses')
    # ### end Alembic commands ###
